# Generated by Django 3.2.5 on 2023-03-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230322_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacoe',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
